Release

diff --git a/.devcontainer/custom_component_helper b/.devcontainer/custom_component_helper
--- a/.devcontainer/custom_component_helper
+++ b/.devcontainer/custom_component_helper
@@ -4,6 +4,9 @@ function StartHomeAssistant {
   echo "Copy configuration.yaml"
   cp -f .devcontainer/configuration.yaml /config || echo ".devcontainer/configuration.yaml are missing!" exit 1
 
+  echo "Copy secrets.yaml"
+  cp -f .devcontainer/secrets.yaml /config || echo ".devcontainer/secrets.yaml are missing!"
+
   echo "Copy the custom component"
   rm -R /config/custom_components/ || echo ""
   cp -r custom_components /config/custom_components/ || echo "Could not copy the custom_component" exit 1
@@ -13,7 +16,7 @@ function StartHomeAssistant {
 }
 
 function UpdgradeHomeAssistantDev {
-  python -m pip install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev
+  python -m pip install --upgrade git+https://github.com/home-assistant/home-assistant@dev
 }
 
 function SetHomeAssistantVersion {
